### ISSUE TITLE
Missing GCC 13+ compatibility

### ISSUE THREAD

**Issue by tina-junold** [pgRouting/pgrouting#2639]
**Problem**
Can't build on alpine 3.20, it was working on 3.18. I assume a problem/incompatibility with the compiler.

**To Reproduce**
I'm building pgrouting with other components in this repository in docker container and combine the compiled libs/binaries later.

https://gitlab.com/ideaplexus/postgis/-/tree/alpine-3.20?ref_type=heads

Checkout the alpine-3.20 branch and run `make pgrouting`

**Expectation**
Should compile

**Sample Data**
Failed to build: https://gitlab.com/ideaplexus/postgis/-/jobs/7502926663
```
[81/198] Building CXX object src/bellman_ford/CMakeFiles/bellman_ford.dir/edwardMoore_driver.cpp.o
ninja: job failed: /usr/bin/c++ -DBOOST_ALLOW_DEPRECATED_HEADERS -DBoost_VERSION_MACRO=108400 -DPGSQL_VERSION=163 -DPROJECT_VERSION=\"3.6.2\" -I/usr/src/pgrouting/include -isystem /usr/local/include/postgresql/server -fPIC  -frounding-math  -O3 -DNDEBUG -std=gnu++14   -Wsign-conversion -MD -MT src/cpp_common/CMakeFiles/cpp_common.dir/rule.cpp.o -MF src/cpp_common/CMakeFiles/cpp_common.dir/rule.cpp.o.d -o src/cpp_common/CMakeFiles/cpp_common.dir/rule.cpp.o -c /usr/src/pgrouting/src/cpp_common/rule.cpp
In file included from /usr/src/pgrouting/src/cpp_common/rule.cpp:26:
/usr/src/pgrouting/include/cpp_common/rule.h:40:34: error: 'int64_t' was not declared in this scope
   40 |     using iterator = std::vector<int64_t>::iterator;
      |                                  ^~~~~~~
/usr/src/pgrouting/include/cpp_common/rule.h:32:1: note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   31 | #include <sstream>
  +++ |+#include <cstdint>
   32 | 
/usr/src/pgrouting/include/cpp_common/rule.h:40:41: error: template argument 1 is invalid
   40 |     using iterator = std::vector<int64_t>::iterator;
```

**Platform/versions**
alpine 3.20
libpqxx 7.9.1
geos 3.12.2
gdal 3.9.1
cgal 5.6.1
sfcgal 1.5.2
proj4 9.4.1
postgis 3.4.2
pgrouting 3.6.2
osm2pgsql 1.11.0
osm2pgrouting 2.3.8

**Comment by tina-junold** [comment]
It seems the issue occurs since alpine 3.19 which uses GCC 13. This requires explicit to include the headers:

https://gcc.gnu.org/gcc-13/porting_to.html

**Comment by tina-junold** [comment]
Sorry for the long delay, haven't seen your message. I tested today with v3.6.3, main and develop, problem still exists...


3.6.3
```
33.57 [87/199] Building CXX object src/components/CMakeFiles/components.dir/articulationPoints_driver.cpp.o
33.59 ninja: job failed: /usr/bin/c++ -DBOOST_ALLOW_DEPRECATED_HEADERS -DPGSQL_VERSION=17000 -DPROJECT_VERSION=\"3.6.3\" -I/usr/src/pgrouting/include -isystem /usr/local/include/postgresql/server -fPIC  -frounding-math  -O3 -DNDEBUG -std=gnu++14   -Wsign-conversion -MD -MT src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o -MF src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o.d -o src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o -c /usr/src/pgrouting/src/cpp_common/Dmatrix.cpp
33.59 In file included from /usr/src/pgrouting/src/cpp_common/Dmatrix.cpp:26:
33.59 /usr/src/pgrouting/include/cpp_common/Dmatrix.h:48:64: error: 'int64_t' was not declared in this scope
33.59    48 |     explicit Dmatrix(const std::map<std::pair<double, double>, int64_t> &euclidean_data);
33.59       |                                                                ^~~~~~~
```


main
```
32.24 [87/199] Building CXX object src/components/CMakeFiles/components.dir/articulationPoints_driver.cpp.o
32.33 In file included from /usr/src/pgrouting/src/cpp_common/Dmatrix.cpp:26:
32.33 /usr/src/pgrouting/include/cpp_common/Dmatrix.h:48:64: error: 'int64_t' was not declared in this scope
32.33    48 |     explicit Dmatrix(const std::map<std::pair<double, double>, int64_t> &euclidean_data);
32.33       |                                                                ^~~~~~~
32.33 /usr/src/pgrouting/include/cpp_common/Dmatrix.h:36:1: note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
32.33    35 | #include <utility>
32.33   +++ |+#include <cstdint>
32.33    36 | 
```

develop
```
33.63 ninja: job failed: /usr/bin/c++ -DBOOST_ALLOW_DEPRECATED_HEADERS -DPGSQL_VERSION=17000 -DPROJECT_VERSION=\"3.7.0\" -I/usr/src/pgrouting/include -isystem /usr/local/include/postgresql/server -fPIC  -frounding-math  -O3 -DNDEBUG -std=gnu++14   -Wsign-conversion -MD -MT src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o -MF src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o.d -o src/cpp_common/CMakeFiles/cpp_common.dir/Dmatrix.cpp.o -c /usr/src/pgrouting/src/cpp_common/Dmatrix.cpp
33.63 In file included from /usr/src/pgrouting/src/cpp_common/Dmatrix.cpp:25:
33.63 /usr/src/pgrouting/include/cpp_common/Dmatrix.hpp:49:64: error: 'int64_t' was not declared in this scope
33.63    49 |     explicit Dmatrix(const std::map<std::pair<double, double>, int64_t> &euclidean_data);
33.63       |                                                                ^~~~~~~
33.63 /usr/src/pgrouting/include/cpp_common/Dmatrix.hpp:37:1: note: 'int64_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
33.63    36 | #include <utility>
33.63   +++ |+#include <cstdint>
```

hope that helps
