### ISSUE TITLE
pgRouting issue compiling with  boost 1.59.0 and CGAL 4.6.1

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#398]
I'm not sure which is at fault here.  I upped debbie's script to use boost 1.59.0 and CGAL 4.6.1 on develop, and failed at compile.  Can't tell which is at fault the cGAL or boost.  I'll try to isolate on my dev machine.  I know pgrouting works with 4.6.1, cause when I swapped out the 4.2 binaries with 4.6.1, the aphashape function still worked.  So bianry wise seems no issue. Boost I have sttically compile sd so not sure about that.

details here:
http://winnie.postgis.net:1500/job/pgRouting_2_PGVersion/2478/console

```
    from e:/jenkins/pgrouting/branches/develop/src/driving_distance/src/alpha_drivedist.cpp:53:
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:105:47: error: macro "accept" requires 3 arguments, but only 2 given
     bool accept(IntType result, WeightType val) const
                                               ^
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:182:36: error: macro "accept" requires 3 arguments, but only 2 given
     bool accept(IntType, WeightType) const
                                    ^
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:436:43: error: macro "accept" requires 3 arguments, but only 2 given
         } while(!_impl.accept(result, test));
                                           ^

In file included from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/number_type_basic.h:60:0,
                 from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/basic.h:44,
                 from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/Cartesian/Cartesian_base.h:28,
                 from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/Simple_cartesian.h:28,
                 from e:/jenkins/pgrouting/branches/develop/src/driving_distance/src/alpha_drivedist.cpp:42:
e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/double.h: In function 'double CGAL::sse2fabs(double)':
e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/double.h:135:5: warning: 'align' attribute directive ignored [-Wattributes]
   } absMask = {0x7fffffffffffffff, 0x7fffffffffffffff};
     ^

In file included from e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random.hpp:62:0,
                 from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/spatial_sort.h:31,
                 from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/Triangulation_2.h:42,
                 from e:/jenkins/CGAL/rel-cgal-4.6.1w64gcc48/include/CGAL/Delaunay_triangulation_2.h:28,
                 from e:/jenkins/pgrouting/branches/develop/src/driving_distance/src/alpha_drivedist.cpp:53:
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp: At global scope:
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:105:10: error: expected ';' at end of member declaration
     bool accept(IntType result, WeightType val) const
          ^
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:106:5: error: expected unqualified-id before '{' token
     {
     ^
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:182:10: error: expected ';' at end of member declaration
     bool accept(IntType, WeightType) const
          ^
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:183:5: error: expected unqualified-id before '{' token
     {
```

**Comment by robe2** [comment]
Okay I checked on my dev machine.  Issue seems to be with CGAL 4.6.1.  If I keep boost at 1.59.0 and switch back to CGAL 4.2 I was using before, it compiles fine.  Howver like I mentioend before, the pgrouting I compile with CGAL 4.2, seems to work fien with CGAL 4.6.1 binaries (run alphashape examples in docs and get same answer)

**Comment by cvvergara** [comment]
This looks like boost error:
e:/jenkins/boost/rel-1_59_0w64gcc48/include/boost-1_59/boost/random/discrete_distribution.hpp:105:10: error: expected ';' at end of member declaration

**Comment by sanak** [comment]
I encountered the same issue on Windows 7 VS2013 build environment.
* boost 1.58.0
* CGAL 4.6.1
* PostgreSQL 9.4.8 (x64)

**Comment by sanak** [comment]
About MSVC build, changing `#include "alpha.h"` order solved the issue.
https://github.com/pgRouting/pgrouting/commit/afbde5bb6b6ff908f1608be48ac13ecdc70b6c41#diff-6facc54e3427aaa4852a680b7c102f09R54

**Comment by cvvergara** [comment]
Its compiling on Jenkins...
I created a label windows, and optimistcally set the milestone to 2.3
