### ISSUE TITLE
Cannot install extension on PostgreSQL 9.6 with pgrouting 2.0

### ISSUE THREAD

**Issue by devrimgunduz** [pgRouting/pgrouting#688]
Hi,

pgrouting 2.0.1 (same results with 2.0.0), and PostgreSQL 9.6. Getting this:

```
postgres=# create extension pgrouting cascade ;
NOTICE:  installing required extension "postgis"
ERROR:  could not load library "/usr/pgsql-9.6/lib/librouting.so": /usr/pgsql-9.6/lib/librouting.so: undefined symbol: heap_formtuple
```

But, I don't get any error with pgrouting 2.0.1 and PostgreSQL 9.4:

```
postgres=# create extension pgrouting;
CREATE EXTENSION
postgres=# \dx
                                      List of installed extensions
   Name    | Version |   Schema   |                             Description   

-----------+---------+------------+-------------------------------------------
--------------------------
 pgrouting | 2.0.0   | public     | pgRouting Extension
 plpgsql   | 1.0     | pg_catalog | PL/pgSQL procedural language
 postgis   | 2.1.5   | public     | PostGIS geometry, geography, and raster sp
atial types and functions
(3 rows)

```

FWIW, 2.2 and 2.3 cannot be compiled on RHEL 6, so I have to stick with 2.0.

Any ideas what may be wrong?

Thanks!

Regards, Devrim

**Comment by cvvergara** [comment]
@devrimgunduz what about 2.1 does it compile?

**Comment by devrimgunduz** [comment]
Well, 2.1 gives errors, and Christoph just sent an email to yum list:

```
commit 726117243022178e72966cbffdfb9147ec6dbbcc
Author: Heikki Linnakangas <heikki.linnakangas@iki.fi>
Date:   Thu Jul 2 21:18:04 2015 +0300

    Remove obsolete heap_formtuple/modifytuple/deformtuple functions.
    
    These variants used the old-style 'n'/' ' NULL indicators. The new-style
    functions have been available since version 8.1. That should be long enough
    that if there is still any old external code using these functions, they
    can just switch to the new functions without worrying about backwards
    compatibility
    
    Peter Geoghegan
```

Given that 2.0 is not under maintenance, not sure what we'll do.

**Comment by cvvergara** [comment]
2.1 compiles in other postgresql other than 9.6?

**Comment by woodbri** [comment]
@devrimgunduz please compile tag 2.1 and let us know what issues you have against pg9.6, we might be able to make a 2.1.1 release that resolves your issues for CENTOS. But we need more information first.

**Comment by robe2** [comment]
2.1 is not supported in PostgreSQL 9.6, we only patched pgRouting 2.2 as I recall.

**Comment by robe2** [comment]
If we want this to work in 2.1, I assume we would need to make the same commits as https://github.com/pgRouting/pgrouting/releases/tag/pgrouting-2.2.3  

I think that was the major reason @cvvergara  did a 2.2.3 release (was to support PostgreSQL 9.6) 

https://github.com/pgRouting/pgrouting/issues/549

**Comment by cvvergara** [comment]
so I'll create a 2.1.1 that works focus on:
- removing the g++0x range loops (if any, there might be one or two but not many) 
- fixes  the heap_formtuple

basically make sure 2.1 works on postgres 9.6

**Comment by woodbri** [comment]
@devrimgunduz Do you know if there is an easy way to setup a CENTOS build bot for testing pgrouting?

**Comment by robe2** [comment]
@devrimgunduz  ah so 2.0 doesn't work for you because of the extension thing.

That's an easy fix I think.  I think a change was made in pgRouting to depend on PostGIS.

So if you didn't compile PostGIS with raster support (as I recall you saying you couldn't with lower CentOS/RHEL), you wouldn't be able to do

`
CREATE EXTENSION pgrouting;
`

The fix I think is for us for at least in pgRouting 2.0, to take out the 

depends on postgis in the pgrouting.control file

**Comment by cvvergara** [comment]
in 2.0 there is still the probem of the "heap_formTuple" and generates alike 5 libraries instead of 1

**Comment by cvvergara** [comment]
I do prefeer to make 2.1 patch

**Comment by woodbri** [comment]
Here is how to setup travis to build CENTOS

https://djw8605.github.io/2016/05/03/building-centos-packages-on-travisci/

**Comment by cvvergara** [comment]
created the working branch
https://github.com/pgRouting/pgrouting/tree/release/2.1.1

**Comment by woodbri** [comment]
@devrimgunduz Can you create a travis.yml based on the above that loads all the dependencies needed to compile pgrouting and post it to a gist or a pull request against a branch that @cvvergara has created so we can use it for testing a pgrouting 2.1.1 on CENTOS.

**Comment by devrimgunduz** [comment]
Sorry, I did not work with travis before, so don't trust me on that :(

**Comment by woodbri** [comment]
I think we might want to look at two different approaches to solving this problem
* get pgr 2.1 to compile on g++ 4.4 and working with pg 9.6
  * The 2.1 path has a few range for loops and needs tuple issue fixed.
* get pgr 2.2 to compile on g++ 4.4 and working with pg 9.6
  * The 2.2 path has more range for loops but already works for 9.6
  * this also has the advantage that lots of other fixes are in the code.

The pgr 2.2 path could be assessed by download the 4.4 compiler and seeing how many files need to be changed.

This is only an idea as it might be faster to do the 2.2 path and give better code to the CENTOS users. I'll leave the decision to @cvvergara

**Comment by woodbri** [comment]
@devrimgunduz please look at the file, ultimately, you are just installing packages and dependencies for CENTOS that are needed to build pgrouting and you would know what is needed for that. You will need to help us on the CENTOS specific side of things.

**Comment by devrimgunduz** [comment]
Getting these in 2.1 on RHEL 6 :(

```
[ 43%] Building CXX object src/common/src/CMakeFiles/common.dir/basePath_SSEC.cpp.o
cd /var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/build/src/common/src && /usr/lib64/ccache/c++    -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -fPIC -O2 -g -Wall -std=c++0x -frounding-math -Wno-deprecated -O3 -DNDEBUG -I/usr/pgsql-9.6/include/server -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/apsp_johnson/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/apsp_warshall/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/astar/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/bd_astar/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/bd_dijkstra/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/dijkstra/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/driving_distance/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/kdijkstra/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/ksp/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/trsp/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/tsp/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/vrp_basic/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/vrppdtw/src -I/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/label_graph/src    -o CMakeFiles/common.dir/basePath_SSEC.cpp.o -c /var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.cpp
In file included from /var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.cpp:29:
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'int collapse_paths(pgr_path_element3_t**, const std::deque<Path, std::allocator<Path> >&)':
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:102: error: expected initializer before ':' token
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected primary-expression before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected ';' before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected primary-expression before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:106: error: expected ')' before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'Path equi_cost(const Path&, const Path&)':
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before '[' token
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before ']' token
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before 'const'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected primary-expression before 'const'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:115: error: expected unqualified-id before 'bool'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:119: error: expected initializer before ':' token
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected primary-expression at end of input
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected ';' at end of input
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected primary-expression at end of input
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected ')' at end of input
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected statement at end of input
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: error: expected '}' at end of input
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:133: warning: no return statement in function returning non-void
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'Path equi_cost(const std::deque<Path, std::allocator<Path> >&)':
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:137: error: expected initializer before ':' token
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected primary-expression before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected ';' before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected primary-expression before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:140: error: expected ')' before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp: In function 'int count_tuples(const std::deque<Path, std::allocator<Path> >&)':
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:145: error: expected initializer before ':' token
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected primary-expression before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected ';' before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected primary-expression before 'return'
/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/src/common/src/basePath_SSEC.hpp:148: error: expected ')' before 'return'
make[3]: *** [src/common/src/CMakeFiles/common.dir/basePath_SSEC.cpp.o] Error 1
make[3]: Leaving directory `/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/build'
make[2]: *** [src/common/src/CMakeFiles/common.dir/all] Error 2
make[2]: Leaving directory `/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/var/lib/pgsql/git/pgrpms/rpm/redhat/9.6/pgrouting/EL-6/pgrouting-pgrouting-2.1.0/build'
error: Bad exit status from /var/tmp/rpm-tmp.5lDLKA (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.5lDLKA (%build)
make: *** [nopreprpm] Error 1

```

**Comment by cvvergara** [comment]
@devrimgunduz 
So, here is the thing:
I really don't want to, in my computer, to compile postgresql in using gcc-4.4, so:
I guess that you use gcc 4.4 to compile Postgresql on RHEL 6

I just pushed some changes to this branch: https://github.com/pgRouting/pgrouting/tree/release/2.1.1
here is the pull request:
https://github.com/pgRouting/pgrouting/pull/689

So, I'll push and you test the branch & post results so I can modify please.
can you test the branch with other postgres than 9.6 please.

**Comment by woodbri** [comment]
@devrimgunduz Please compile and test the 2.1.1 code (see url above) and verify that it compiles and works on CENTOS 6 with the GCC 4.4 compiler and postgresql 9.6 and any other versions you care about. You need to confirm or update this issue if you find problems and then we can release it.

This fix changed over 100 files. We do not plan to make a 2.2 or 2.3 release for CENTOS as they are much more difficult and invasive changes unless there is someone interested in funding those changes.

Here is a link to Vicky's task list: https://github.com/cvvergara/pgrouting/issues/60

**Comment by cvvergara** [comment]
automatic tests done:
Travis:
https://travis-ci.org/pgRouting/pgrouting/builds/164376093
Jenkins:
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_cvvergara_repo/57/

**Comment by cvvergara** [comment]
@devrimgunduz 
I managed to compile using GNU 4.4 and I am getting this errors (basically in all *.c files):
```
[ 94%] Building C object src/vrp_basic/src/CMakeFiles/vrp_basic.dir/VRP.c.o
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP.c: In function ‘finish’:
/home/vicky/pgrouting/pgrouting/pgrouting/src/vrp_basic/src/VRP.c:149: warning: implicit declaration of function ‘__builtin_unreachable’
```
after compilation when I start executing the tests the extension does not load because __builtin_unreachable is not defined:
```
CREATE EXTENSION
ERROR:  could not load library "/usr/lib/postgresql/9.3/lib/librouting-2.1.so": /usr/lib/postgresql/9.3/lib/librouting-2.1.so: undefined symbol: __builtin_unreachable
ERROR:  function pgr_version() does not exist
LINE 1: select pgr_version()
```
The errors are where `elog(ERROR` is used so I get the error maybe because of my postgreSQL instalation

__builtin_unreachable started on GCC 4.5:
https://gcc.gnu.org/onlinedocs/gcc-4.5.4/gcc/Other-Builtins.html

I really need someone to test this branch on Centos 6:
https://github.com/pgRouting/pgrouting/tree/release/2.1.1
which will use the postgresql's elog function compiled using 4.4 and somehow its providing `__builtin_unreachable`
That test before I try the several suggestions mentioned:
http://stackoverflow.com/questions/6031819/emulating-gccs-builtin-unreachable

PS.
pgRouting relies heavily on C++ code you can see the difference of the things that can be done on the g++4.4 used by Centos 6 and the g++4.8 used in Centos 7
https://gcc.gnu.org/gcc-4.4/cxx0x_status.html
https://gcc.gnu.org/gcc-4.8/cxx0x_status.html
Hopefully we can get at least the 2.1.1working for Centos 6

**Comment by cvvergara** [comment]
I'll rephrase:

> which will use the postgresql's elog function compiled using 4.4 and somehow its providing __builtin_unreachable

to:


which will use the postgresql's elog function compiled using 4.4 and somehow its either: providing or not even using __builtin_unreachable.

**Comment by dkastl** [comment]
@devrimgunduz after evaluating the issue and estimating the effort to support pgRouting with PostgreSQL 9.6 and CentOS 6, we came to the conclusion, that this would require some contribution or funding.

I'm not sure how many people would be affected, but my guess is, that upgrading to the most recent version of PostgreSQL may also justify to upgrade CentOS to a newer release in many cases. So users of CentOS 6 had to continue an elder version of PostgreSQL/pgRouting.
Maybe there are other ways to enable support for C++11, which pgRouting requires now, but this is out of scope of pgRouting. 
Of course patches, contributions or funding is welcome, but otherwise I will close this ticket for now.
