### ISSUE TITLE
Can't build on 9.3 64-bit windows v2.4.0-rc0

### ISSUE THREAD

**Issue by robe2** [pgRouting/pgrouting#747]
### Expected behavior and actual behavior
I was trying to build pgRouting rc0 tag for windows, and it's erroring when building for 9.3x64-bt.
The 9.4, 9.5 and 9.6 seemed to have built and regressed okay

If it doesn't work under 9.3 and can't work, we should just make a note of it. 
Note I don't plan to package 2.4 for 9.3 (it will only be available for download for those that want it.) so not super critical for me.  I suspect also not for most packagers since they try to marry versions of extensions with PostgreSQL and only ship one version of extension alongside PostgreSQL version.

The output in compile I get is this:

``
                 from e:/jenkins/pgrouting/branches/2.4.0-rc/src/withPoints/src/many_to_many_withPoints_driver.cpp:44:
e:/jenkins/postgresql/rel/pg9.3w64gcc48/include/server/pg_config_os.h:215:8: error: redefinition of 'struct itimerval'
 struct itimerval
        ^
In file included from e:/jenkins/postgresql/rel/pg9.3w64gcc48/include/server/c.h:57:0,
                 from e:/jenkins/postgresql/rel/pg9.3w64gcc48/include/server/postgres.h:47,
                 from e:/jenkins/pgrouting/branches/2.4.0-rc/src/withPoints/src/./../../common/src/./postgres_connection.h:34,
                 from e:/jenkins/pgrouting/branches/2.4.0-rc/src/withPoints/src/./../../common/src/pgr_alloc.hpp:31,
                 from e:/jenkins/pgrouting/branches/2.4.0-rc/src/withPoints/src/many_to_many_withPoints_driver.cpp:44:
e:/jenkins/postgresql/rel/pg9.3w64gcc48/include/server/pg_config_os.h:215:8: error: previous definition of 'struct itimerval'
 struct itimerval
        ^
src/withPoints/src/CMakeFiles/withPoints.dir/build.make:205: recipe for target `src/withPoints/src/CMakeFiles/withPoints.dir/many_to_many_withPoints_driver.cpp.obj' failed
make[2]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/many_to_many_withPoints_driver.cpp.obj] Error 1
make[2]: Leaving directory `/projects/pgrouting/build2.4.0-rcw64gcc48'
CMakeFiles/Makefile2:951: recipe for target `src/withPoints/src/CMakeFiles/withPoints.dir/all' failed
make[1]: *** [src/withPoints/src/CMakeFiles/withPoints.dir/all] Error 2
make[1]: Leaving directory `/projects/pgrouting/build2.4.0-rcw64gcc48'
Makefile:119: recipe for target `all' failed
make: *** [all] Error 2

``
### Steps to reproduce the problem
this is building under winnie mingw64 that uses gcc 4.8.2

### Specifications like the version of pgRouting/PostGIS and PostgreSQL as well as Operating System
pgRouting v2.4.0-rc0

**Comment by cvvergara** [comment]
Going to be fixed on v2.4.0-rc1
http://winnie.postgis.net:1500/view/pgRouting/job/pgRouting_matrix_branch_2_4/4/
