### ISSUE TITLE
2.4.0 fails to compile on macOS

### ISSUE THREAD

**Issue by fxcoudert** [pgRouting/pgrouting#767]
Observed in Homebrew builds in macOS (10.10, 10.11 and 10.12):

```
[ 72%] Building C object src/max_flow/src/CMakeFiles/max_flow.dir/max_flow_many_to_one.c.o
cd /tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/build/src/max_flow/src && /usr/local/Homebrew/Library/Homebrew/shims/super/clang   -I/usr/local/Cellar/postgresql/9.6.2/include/server -I/usr/local/include -I/tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/common/src -I/tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/dijkstra/src  -DPGSQL_VERSION=96  -std=gnu99 -fPIC  -frounding-math  -DNDEBUG -DPGSQL_VERSION=96 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.10   -o CMakeFiles/max_flow.dir/max_flow_many_to_one.c.o   -c /tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/max_flow/src/max_flow_many_to_one.c
In file included from /tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/bdDijkstra/src/bdDijkstra_driver.cpp:35:
/tmp/pgrouting-20170322-49396-8xp85v/pgrouting-2.4.0/src/bdDijkstra/src/./pgr_bdDijkstra.hpp:84:24: error: reference to non-static member function must be called
     void clean_log() {log.clear();}
                       ^~~
```

**Comment by fxcoudert** [comment]
Full build log is there: https://gist.github.com/fxcoudert/9266be582c22507104e22d09896bb9b2
Homebrew issue: https://github.com/Homebrew/homebrew-core/pull/11365

**Comment by cvvergara** [comment]
@fxcoudert 
Hello, 
I can not test changes on macOS, I don't have one and I don't know how to prepare travis for macOS.

The compilation stops, after finding the error so I don't know if after fixing that error other can show up. 

Can you edit:
src/bdDijkstra/src/pgr_bdDijkstra.hpp

and change line: 84 to be
```
void clean_log() {m_log.clear();}
```
and recompile again, just to verify that is the only thing that the macOS compiler finds.

This are the travis builds with the change I mention.

https://travis-ci.org/cvvergara/pgrouting/builds/214310203

Note: trsp, which it hasn't being rewritten, has many warnings on this builds. Hopefully non of this warnings is considered an error on macOS compiler

do you know how to prepare travis to also test using macOS?
