### ISSUE TITLE
Release of v3.0.0

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/pgrouting#1243]
# Main tasks:

- [x] release v2.6.3
- [x] release v3.0.0-alpha
- [x] release v3.0.0-beta
- [x] release v3.0.0-rc1
- [x] release v3.0.0

Steps for each task in a separate comment on this issue

**Comment by cvvergara** [comment]
# release v2.6.3

On master
- [ ] pump up to version 2.6.3
  - [ ] make sure release_notes and NEWS are OK
- [ ] commit changes and push into `release/2.6` branch
- [ ] [travis](https://travis-ci.org/pgRouting/pgrouting/builds/580810430) pass
- [ ] create `v2.6.3` tag & push
- [ ] modify [tag v2.6.3](https://github.com/pgRouting/pgrouting/releases/tag/v2.6.3)
  - Add comments
  - set as release

**Comment by cvvergara** [comment]
# release v3.0.0-alpha

On master
- [ ] merge develop into master
- [ ] make sure release_notes and NEWS are OK
- [ ] update the Readme.md if necessary
- [ ] commit changes and push master
- [ ] create `v3.0.0-alpha` tag & push tag
- [ ] modify [tag v3.0.0-alpha](https://github.com/pgRouting/pgrouting/releases/tag/v3.0.0-alpha)
  - Add comments
  - Set as non production ready

**Comment by cvvergara** [comment]
# release v3.0.0-beta

On master
- [x] make sure release_notes and NEWS are OK
- [x] update the Readme.md if necessary
- [x] verify contributors names are complete
- [x] make PR of chages
- [x] merge develop into master
- [x] fix clonflicts and commit
- [x] pump version to v3.0.0-beta
- [x] push master
- [x] do verifications
- [x] create `v3.0.0-beta` tag & push tag
- [x] modify [tag v3.0.0-beta](https://github.com/pgRouting/pgrouting/releases/tag/v3.0.0-beta)
  - Add comments
  - Set as non production ready

**Comment by cvvergara** [comment]
# release v3.0.0-rc1

On master
- [ ] make sure release_notes and NEWS are OK
- [ ] update the Readme.md if necessary
- [ ] verify contributors names are complete
- [ ] make PR of chages
- [ ] merge develop into master
- [ ] fix clonflicts and commit
- [ ] pump version to v3.0.0-rc1
- [ ] push master
- [ ] do verifications
- [ ] create `v3.0.0-rc1` tag & push tag
- [ ] modify [tag v3.0.0-beta](https://github.com/pgRouting/pgrouting/releases/tag/v3.0.0-rc1)
  - Add comments
  - Set as non production ready

**Comment by devrimgunduz** [comment]
Hi @cvvergara ,

The CentOS 7 issue is still there with rc1:
/var/lib/pgsql/rpm12/BUILD/pgrouting-3.0.0-rc1/include/boost/bgeometry/core/access.hpp:20:40: fatal error: boost/core/ignore_unused.hpp: No such file or directory
 #include <boost/core/ignore_unused.hpp>
                                        ^
compilation terminated.

**Comment by dkastl** [comment]
@devrimgunduz , do you mean this issue?
https://github.com/pgRouting/pgrouting/issues/1258

**Comment by fljdin** [comment]
Hi @devrimgunduz 
Compilation works with boost-graph (BGL) in 1.56.0 in replacement of 1.53 as documented.
Regards

**Comment by devrimgunduz** [comment]
@fljdin  Thanks for the  tip. Can you please let me know how can I tell pgRouting to use that custom-ish boost package (it's going to be boost169 on RHEL 7)

Thanks!

**Comment by cvvergara** [comment]
@devrimgunduz I will make the release, I did try to use 1.53

**Comment by devrimgunduz** [comment]
@cvvergara  Please release. We will fix it this way or another :)
